#!/bin/sh


PATH=/sbin:/bin:/usr/sbin:/usr/bin
runlevel=S
prevlevel=N
umask 022
export PATH runlevel prevlevel

mount -a
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts
#mount -n -t usbfs none /proc/bus/usb
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s
mkdir -p /var/lock

ifconfig lo 127.0.0.1
ifconfig eth0 192.168.137.133

# Netwroking
ifconfig eth0 up > /dev/null 2>&1
ifconfig eth0 192.168.137.5
route add default gw 192.168.137.1

# start telnetd
/usr/sbin/telnetd &



/bin/hostname -F /etc/sysconfig/HOSTNAME
