#!/bin/bash
switch=br0
interface=eth0
tap0_exit=`ifconfig | grep $1`

if [ ! -n "$tap0_exit" ]; then
if [ -n "$1" ]; then
	switch_exit=`sudo ifconfig -a | grep $switch`
	interface_switch=`sudo brctl show | grep $interface`
	if [ "$switch_exit" = "" ] ; then
		sudo brctl addbr $switch 
	fi

	if [ "$interface_switch" = "" ] ; then
		sudo ifconfig $interface 0.0.0.0 promisc up
		sudo brctl addif $switch $interface
	fi

	sudo ifconfig $1 0.0.0.0 promisc up
	sudo brctl addif $switch $1
	sudo dhclient $switch
else
	echo "Error: no interface specified"
	exit
fi

	  
else
	  
	echo "$1 exits,not need to create $1"
	  
fi


